name: Update SVG
on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Fetch data and generate SVG
        run: |
          python scripts/fetch_data.py
          python scripts/generate_svg.py
      - name: Commit and push changes
        run: |
          git config --local user.name "${{ vars.USER_EMAIL }}"
          git config --local user.email "${{ vars.USER_NAME }}"
          git status
          git add assets/terminal.svg
          git status
          git commit -m "Update terminal SVG"
          git push

